export const listaDelegacias = [
    {value: '01ª DP', label: '01ª DP'},
    {value: '02ª DP', label: '02ª DP'},
    {value: '03ª DP', label: '03ª DP'},
    {value: '04ª DP', label: '04ª DP'},
    {value: '05ª DP', label: '05ª DP'},
    {value: '06ª DP', label: '06ª DP'},
    {value: '08ª DP', label: '08ª DP'},
    {value: '09ª DP', label: '09ª DP'},
    {value: '10ª DP', label: '10ª DP'},
    {value: '11ª DP', label: '11ª DP'},
    {value: '12ª DP', label: '12ª DP'},
    {value: '13ª DP', label: '13ª DP'},
    {value: '14ª DP', label: '14ª DP'},
    {value: '15ª DP', label: '15ª DP'},
    {value: '16ª DP', label: '16ª DP'},
    {value: '17ª DP', label: '17ª DP'},
    {value: '18ª DP', label: '18ª DP'},
    {value: '19ª DP', label: '19ª DP'},
    {value: '20ª DP', label: '20ª DP'},
    {value: '21ª DP', label: '21ª DP'},
    {value: '23ª DP', label: '23ª DP'},
    {value: '24ª DP', label: '24ª DP'},
    {value: '26ª DP', label: '26ª DP'},
    {value: '27ª DP', label: '27ª DP'},
    {value: '29ª DP', label: '29ª DP'},
    {value: '30ª DP', label: '30ª DP'},
    {value: '31ª DP', label: '31ª DP'},
    {value: '32ª DP', label: '32ª DP'},
    {value: '33ª DP', label: '33ª DP'},
    {value: '35ª DP', label: '35ª DP'},
    {value: '38ª DP', label: '38ª DP'},
    {value:'DEAM', label:'DEAM'},
    {value:'DCA', label:'DCA'},
    {value:'DCA II', label:'DCA II'},
    {value:'DPE', label:'DPE'}
]