export const listaGraduacoes =[
    { value: 'Sd 2ª CL', label: 'Soldado 2ª Classe'},
    { value: 'Sd', label: 'Soldado'},
    { value: 'Cb', label: 'Cabo'},
    { value: '3º Sgt', label: '3º Sargento'},
    { value: '2º Sgt', label: '2º Sargento'},
    { value: '1º Sgt', label: '1º Sargento'},
    { value: 'ST', label: 'SubTenente'},
    { value: 'Cadete 1º ano', label: 'Cadete 1º ano'},
    { value: 'Cadete 2º ano', label: 'Cadete 2º ano'},
    { value: 'Cadete 3º ano', label: 'Cadete 3º ano'},
    { value: 'Asp', label: 'Aspirante'},
    { value: '2º Ten', label: '2º Tenente'},
    { value: '1º Ten', label: '1º Tenente'},
    { value: 'Cap', label: 'Capitão'},
    { value: 'Maj', label: 'Major'},
    { value: 'TC', label: 'Tenente-Coronel'},
    { value: 'Cel', label: 'Coronel'},
]