export const listaNaturezas = [
    { value: 'Apreensão de substância entorpecente', label: 'Apreensão de substância entorpecente' },
    { value: 'Apreensão de arma de fogo', label: 'Apreensão de arma de fogo' },
    { value: 'Apreensão de veículo roubado', label: 'Apreensão de veículo roubado' },
    { value: 'Apreensão de veículo furtado', label: 'Apreensão de veículo furtado' },
    { value: 'Apreensão de simulacro de arma de fogo', label: 'Apreensão de simulacro de arma de fogo' },
    { value: 'Arma de fogo encontrada', label: 'Arma de fogo encontrada' },
    { value: 'Corrupção ativa', label: 'Corrupção ativa' },
    { value: 'Desacato', label: 'Desacato' },
    { value: 'Desobediência', label: 'Desobediência' },
    { value: 'Desobediência', label: 'Desobediência' },
    { value: 'Homicídio', label: 'Homicídio' },
    { value: 'Homofobia', label: 'Homofobia' },
    { value: 'Latrocínio', label: 'Latrocínio' },
    { value: 'Racismo', label: 'Racismo' },
    { value: 'Receptação', label: 'Receptação' },
    { value: 'Tortura', label: 'Tortura' },
    { value: 'Abandono de menor', label: 'Abandono de menor' },
    { value: 'Abandono de idoso', label: 'Abandono de idoso' },
    { value: 'Abandono de incapaz', label: 'Abandono de incapaz' },
    { value: 'Acidente de trânsito com vítima', label: 'Acidente de trânsito com vítima' },
    { value: 'Acidente de trânsito sem vítima', label: 'Acidente de trânsito sem vítima' },
    { value: 'Alarme acionado', label: 'Alarme acionado' },
    { value: 'Ameaça', label: 'Ameaça' },
    { value: 'Estupro', label: 'Estupro' },
    { value: 'Assédio sexual', label: 'Assédio sexual' },
    { value: 'Ato obsceno', label: 'Ato obsceno' },
    { value: 'Dano ao patrimônio público', label: 'Dano ao patrimônio público' },
    { value: 'Dano ao patrimônio privado', label: 'Dano ao patrimônio privado' },
    { value: 'Tráfico de drogas', label: 'Tráfico de drogas' },
    { value: 'Uso e porte de substância entorpecente', label: 'Uso e porte de substância entorpecente' },
    { value: 'Dano', label: 'Dano' },
    { value: 'Maus tratos a animais', label: 'Maus tratos a animais' },
    { value: 'Abandono de animais', label: 'Abandono de animais' },
    { value: 'Omissão de cautela de animais', label: 'Omissão de cautela de animais' },
    { value: 'Roubo a transeunte', label: 'Roubo a transeunte' },
    { value: 'Roubo a estabelecimento comercial', label: 'Roubo a estabelecimento comercial' },
    { value: 'Roubo de veículo', label: 'Roubo de veículo' },
    { value: 'Suicídio', label: 'Suicídio' },
    { value: 'Vias de fato', label: 'Vias de fato' },
    { value: 'Agressão física', label: 'Agressão física' },
    { value: 'Violência doméstica', label: 'Violência doméstica' },
    { value: 'Perturbação do sossego em residência', label: 'Perturbação do sossego em residência' },
    { value: 'Perturbação do sossego em veículo', label: 'Perturbação do sossego em veículo' },
    { value: 'Perturbação do sossego em estabelecimento comercial', label: 'Perturbação do sossego em estabelecimento comercial' },
    { value: 'Embriaguez ao volante', label: 'Embriaguez ao volante' },

]