export const listaParentesco = [
    { value: 'marido', label: 'Marido' },
    { value: 'ex-marido', label: 'Ex-marido' },
    { value: 'esposa', label: 'Esposa' },
    { value: 'ex-esposa', label: 'Ex-esposa' },
    { value: 'companheiro(a)', label: 'Companheiro(a)' },
    { value: 'ex-companheiro(a)', label: 'Ex-companheiro(a)' },
    { value: 'namorado', label: 'Namorado(a)' },
    { value: 'ex-namorado', label: 'Ex-namorado(a)' },
    { value: 'pai', label: 'Pai' },
    { value: 'mãe', label: 'Mãe' },
    { value: 'filho(a)', label: 'Filho(a)' },
    { value: 'irmão(a)', label: 'Irmão(ã)' },
    { value: 'tio(a)', label: 'Tio(a)' },
    { value: '', label: 'Outro' },
    { value: 'desconhecido', label: 'Desconhecido' },
]