export const regioesAdministrativas = [
    { value: 'Plano Piloto', label: 'RA I - Plano Piloto' },
    { value: 'Gama', label: 'RA II - Gama' },
    { value: 'Taguatinga', label: 'RA III - Taguatinga' },
    { value: 'Brazlândia', label: 'RA IV - Brazlândia' },
    { value: 'Sobradinho', label: 'RA V - Sobradinho' },
    { value: 'Planaltina', label: 'RA VI - Planaltina' },
    { value: 'Paranoá', label: 'RA VII - Paranoá' },
    { value: 'Núcleo Bandeirante', label: 'RA VIII - Núcleo Bandeirante' },
    { value: 'Ceilândia', label: 'RA IX - Ceilândia' },
    { value: 'Guará', label: 'RA X - Guará' },
    { value: 'Cruzeiro', label: 'RA XI - Cruzeiro' },
    { value: 'Samambaia', label: 'RA XII - Samambaia' },
    { value: 'Santa Maria', label: 'RA XIII - Santa Maria' },
    { value: 'São Sebastião', label: 'RA XIV - São Sebastião' },
    { value: 'Recanto das Emas', label: 'RA XV - Recanto das Emas' },
    { value: 'Lago Sul', label: 'RA XVI - Lago Sul' },
    { value: 'Riacho Fundo', label: 'RA XVII - Riacho Fundo' },
    { value: 'Lago Norte', label: 'RA XVIII - Lago Norte' },
    { value: 'Candangolândia', label: 'RA XIX - Candangolândia' },
    { value: 'Águas Claras', label: 'RA XX - Águas Claras' },
    { value: 'Riacho Fundo 2', label: 'RA XXI - Riacho Fundo 2' },
    { value: 'Sudoeste', label: 'RA XXII - Sudoeste' },
    { value: 'Octogonal', label: 'RA XXII - Octogonal' },
    { value: 'Varjão', label: 'RA XXIII - Varjão' },
    { value: 'Park Way', label: 'RA XXIV - Park Way' },
    { value: 'Estrutural', label: 'RA XXV - Estrutural' },
    { value: 'SCIA', label: 'RA XXV - SCIA' },
    { value: 'Sobradinho II', label: 'RA XXVI - Sobradinho II' },
    { value: 'Jardim Botânico', label: 'RA XXVII - Jardim Botânico' },
    { value: 'Itapoã', label: 'RA XXVIII - Itapoã' },
    { value: 'SIA', label: 'RA XXIX - SIA' },
    { value: 'Vicente Pires', label: 'RA XXX - Vicente Pires' },
    { value: 'Fercal', label: 'RA XXXI - Fercal' },
    { value: 'Sol Nascente', label: 'RA XXXII - Sol Nascente' },
    { value: 'Pôr do Sol', label: 'RA XXXII - Pôr do Sol' },
    { value: 'Arniqueira', label: 'RA XXXIII - Arniqueira' },
    { value: 'Arapoanga', label: 'RA XXXIV - Arapoanga' },
    { value: 'Água Quente', label: 'RA XXXV - Água Quente' }]

export const qtdeIndividuos = [
    { value: 'não sabe', label: 'Não sabe' },
    { value: '1', label: '1 indivíduo' },
    { value: '2', label: '2 indivíduos' },
    { value: '3', label: '3 indivíduos' },
    { value: '4', label: '4 indivíduos' },
    { value: '5', label: '5 indivíduos' },
    { value: 'mais de 5', label: 'Mais de 5 indivíduos' }
]

export const cores = [
    { value: 'clara', label: 'Clara' },
    { value: 'escura', label: 'Escura' },
    { value: 'branca', label: 'Branca' },
    { value: 'preta', label: 'Preta' },
    { value: 'azul', label: 'Azul' },
    { value: 'amarela', label: 'Amarela' },
    { value: 'vermelha', label: 'Vermelha' },
    { value: 'colorida', label: 'Outra cor' },
    { value: 'não soube informar', label: 'Não sabe' },
]

export const caracteristicasOption = [
    'barba',
    'bigode',
    'cicatriz',
    'tatuagem',
    'sinal no rosto',
    'outro'
]