export const listaBatalhoes = [
    { value: '1º Batalhão', label: '1º Batalhão'},
    { value: '2º Batalhão', label: '2º Batalhão'},
    { value: '3º Batalhão', label: '3º Batalhão'},
    { value: '4º Batalhão', label: '4º Batalhão'},
    { value: '5º Batalhão', label: '5º Batalhão'},
    { value: '6º Batalhão', label: '6º Batalhão'},
    { value: '7º Batalhão', label: '7º Batalhão'},
    { value: '8º Batalhão', label: '8º Batalhão'},
    { value: '9º Batalhão', label: '9º Batalhão'},
    { value: '10º Batalhão', label: '10º Batalhão'},
    { value: '11º Batalhão', label: '11º Batalhão'},
    { value: '12º Batalhão', label: '12º Batalhão'},
    { value: '13º Batalhão', label: '13º Batalhão'},
    { value: '14º Batalhão', label: '14º Batalhão'},
    { value: '15º Batalhão', label: '15º Batalhão'},
    { value: '16º Batalhão', label: '16º Batalhão'},
    { value: '17º Batalhão', label: '17º Batalhão'},
    { value: '18º Batalhão', label: '18ª Batalhão'},
    { value: '19º Batalhão', label: '19º Batalhão'},
    { value: '20º Batalhão', label: '20º Batalhão'},
    { value: '21º Batalhão', label: '21º Batalhão'},
    { value: '22º Batalhão', label: '22º Batalhão'},
    { value: '23º Batalhão', label: '23º Batalhão'},
    { value: '24º Batalhão', label: '24º Batalhão'},
    { value: '25º Batalhão', label: '25º Batalhão'},
    { value: '26º Batalhão', label: '26º Batalhão'},
    { value: '27º Batalhão', label: '27º Batalhão'},
    { value: '28º Batalhão', label: '28º Batalhão'},
    { value: 'BOPE', label: 'BOPE'},
    { value: 'BPCaes', label: 'BPCaes'},
    { value: 'BPChoque', label: 'BPChoque'},
    { value: 'BPMA', label: 'BPMA'},
    { value: 'BPRural', label: 'BPRural'},
    { value: 'BPRV', label: 'BPRV'},
    { value: 'BPTran', label: 'BPTran'},
    { value: 'PATAMO', label: 'PATAMO'},
    { value: 'ROTAM', label: 'ROTAM'},
    { value: 'RPMon', label: 'RPMon'},
    { value: 'Complexo Administrativo', label: 'Complexo Administrativo'},
]