export const regioesAdministrativas = [
    { value: 'Plano Piloto', label: 'Plano Piloto' },
    { value: 'Gama', label: 'Gama' },
    { value: 'Taguatinga', label: 'aguatinga' },
    { value: 'Brazlândia', label: 'Brazlândia' },
    { value: 'Sobradinho', label: 'Sobradinho' },
    { value: 'Planaltina', label: 'Planaltina' },
    { value: 'Paranoá', label: 'Paranoá' },
    { value: 'Núcleo Bandeirante', label: 'Núcleo Bandeirante' },
    { value: 'Ceilândia', label: 'Ceilândia' },
    { value: 'Guará', label: 'Guará' },
    { value: 'Cruzeiro', label: 'Cruzeiro' },
    { value: 'Samambaia', label: 'Samambaia' },
    { value: 'Santa Maria', label: 'Santa Maria' },
    { value: 'São Sebastião', label: 'São Sebastião' },
    { value: 'Recanto das Emas', label: 'Recanto das Emas' },
    { value: 'Lago Sul', label: 'Lago Sul' },
    { value: 'Riacho Fundo', label: 'Riacho Fundo' },
    { value: 'Lago Norte', label: 'Lago Norte' },
    { value: 'Candangolândia', label: 'Candangolândia' },
    { value: 'Águas Claras', label: 'Águas Claras' },
    { value: 'Riacho Fundo 2', label: 'Riacho Fundo 2' },
    { value: 'Sudoeste', label: 'Sudoeste' },
    { value: 'Octogonal', label: 'Octogonal' },
    { value: 'Varjão', label: 'Varjão' },
    { value: 'Park Way', label: 'Park Way' },
    { value: 'Estrutural', label: 'Estrutural' },
    { value: 'SCIA', label: 'SCIA' },
    { value: 'Sobradinho II', label: 'Sobradinho II' },
    { value: 'Jardim Botânico', label: 'Jardim Botânico' },
    { value: 'Itapoã', label: 'Itapoã' },
    { value: 'SIA', label: 'SIA' },
    { value: 'Vicente Pires', label: 'Vicente Pires' },
    { value: 'Fercal', label: 'Fercal' },
    { value: 'Sol Nascente', label: 'Sol Nascente' },
    { value: 'Pôr do Sol', label: 'Pôr do Sol' },
    { value: 'Arniqueira', label: 'Arniqueira' },
    { value: 'Arapoanga', label: 'Arapoanga' },
    { value: 'Água Quente', label: 'Água Quente' }]

    export const crimes =  [
        { value: 'ameaça', label: 'ameaça' },
        {value: 'agressão física', label: 'agressão física'}]