export const permissions = {

  Administrador: ['Home',
    'Gerar Ocorrência',
    'Verificar Pessoa',
    'Verificar Veículo',
    'Cadastrar Usuário',
    'Violência doméstica',
    'Roubo/Furto',
    'Som automotivo / Perturbação',
    'Crimes contra animais',
    'Alarme acionado',
    'Vias de Fato',
    'Ameaça',
    'Acidente de trânsito',
    'Drogas',
    'Abandono',
    'Crimes Sexuais',
    'Homofobia',
    'Racismo',
    'Suicidio',
    'Pessoa armada',
    'Agressão',
  ],

  Gestor: ['Home',
    'Gerar Ocorrência',
    'Verificar Pessoa',
    'Verificar Veículo',
    'Cadastrar Usuário',
    'Violência doméstica',
    'Roubo/Furto',
    'Som automotivo / Perturbação',
    'Crimes contra animais',
    'Alarme acionado',
    'Vias de Fato',
    'Ameaça',
    'Acidente de trânsito',
    'Drogas',
    'Abandono',
    'Crimes Sexuais',
    'Homofobia',
    'Racismo',
    'Suicidio',
    'Pessoa armada',
    'Agressão',],
  Usuario: [
    'Home',
    'Gerar Ocorrência',
    'Violência doméstica',
    'Roubo/Furto',
    'Som automotivo / Perturbação',
    'Crimes contra animais',
    'Alarme acionado',
    'Vias de Fato',
    'Ameaça',
    'Acidente de trânsito',
    'Drogas',
    'Abandono',
    'Crimes Sexuais',
    'Homofobia',
    'Racismo',
    'Suicidio',
    'Pessoa armada',
    'Agressão'
  ],
  Nivel:[],
  Nivel2:[],
};