export const permissions = {
    Administrador: ['Home', 'Gerar Ocorrência',
      'Verificar Pessoa',
      'Verificar Veículo',
      'Cadastrar Usuario',
      'Violência doméstica',
      'Roubo/Furto',
      'Som automotivo / Perturbação',
      'Crimes contra animais',
      'Alarme acionado',
      'Vias de Fato',
      'Ameaça',
      'Acidente de trânsito',
      'Drogas',
      'Abandono',
      'Crimes Sexuais',
      'Homofobia',
      'Racismo',
      'Suicidio',
      'Pessoa armada',
      'Agressão',
    ],
    Gestor: ['Home', 'Gerar Ocorrência', 'Violência doméstica', 'Roubo/Furto', 'Som automotivo / Perturbação'],
  };